// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: gateway.proto

package goftxlogistics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWindowWindowSizeSelector int32

const (
	GetWindow_w15    GetWindowWindowSizeSelector = 0
	GetWindow_w60    GetWindowWindowSizeSelector = 60
	GetWindow_w300   GetWindowWindowSizeSelector = 300
	GetWindow_w900   GetWindowWindowSizeSelector = 900
	GetWindow_w3600  GetWindowWindowSizeSelector = 3600
	GetWindow_w14400 GetWindowWindowSizeSelector = 14400
	GetWindow_w86400 GetWindowWindowSizeSelector = 86400
)

// Enum value maps for GetWindowWindowSizeSelector.
var (
	GetWindowWindowSizeSelector_name = map[int32]string{
		0:     "w15",
		60:    "w60",
		300:   "w300",
		900:   "w900",
		3600:  "w3600",
		14400: "w14400",
		86400: "w86400",
	}
	GetWindowWindowSizeSelector_value = map[string]int32{
		"w15":    0,
		"w60":    60,
		"w300":   300,
		"w900":   900,
		"w3600":  3600,
		"w14400": 14400,
		"w86400": 86400,
	}
)

func (x GetWindowWindowSizeSelector) Enum() *GetWindowWindowSizeSelector {
	p := new(GetWindowWindowSizeSelector)
	*p = x
	return p
}

func (x GetWindowWindowSizeSelector) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetWindowWindowSizeSelector) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_proto_enumTypes[0].Descriptor()
}

func (GetWindowWindowSizeSelector) Type() protoreflect.EnumType {
	return &file_gateway_proto_enumTypes[0]
}

func (x GetWindowWindowSizeSelector) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetWindowWindowSizeSelector.Descriptor instead.
func (GetWindowWindowSizeSelector) EnumDescriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0, 0}
}

// Default window size is 4 hours (14400 (in seconds))
type GetWindow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WindowSize GetWindowWindowSizeSelector `protobuf:"varint,14400,opt,name=windowSize,proto3,enum=main.GetWindowWindowSizeSelector" json:"windowSize,omitempty"`
}

func (x *GetWindow) Reset() {
	*x = GetWindow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWindow) ProtoMessage() {}

func (x *GetWindow) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWindow.ProtoReflect.Descriptor instead.
func (*GetWindow) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetWindow) GetWindowSize() GetWindowWindowSizeSelector {
	if x != nil {
		return x.WindowSize
	}
	return GetWindow_w15
}

type WindowDataArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime string  `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Time      uint64  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Open      float64 `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	High      float64 `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`
	Low       float64 `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`
	Close     float64 `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume    float64 `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *WindowDataArray) Reset() {
	*x = WindowDataArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowDataArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowDataArray) ProtoMessage() {}

func (x *WindowDataArray) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowDataArray.ProtoReflect.Descriptor instead.
func (*WindowDataArray) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *WindowDataArray) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *WindowDataArray) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *WindowDataArray) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *WindowDataArray) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *WindowDataArray) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *WindowDataArray) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *WindowDataArray) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_gateway_proto protoreflect.FileDescriptor

var file_gateway_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xb5, 0x01, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x57, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x12, 0x43, 0x0a, 0x0a, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0xc0, 0x70, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x67, 0x65, 0x74, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x53, 0x69, 0x7a, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x63, 0x0a, 0x12, 0x77, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x07,
	0x0a, 0x03, 0x77, 0x31, 0x35, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x77, 0x36, 0x30, 0x10, 0x3c,
	0x12, 0x09, 0x0a, 0x04, 0x77, 0x33, 0x30, 0x30, 0x10, 0xac, 0x02, 0x12, 0x09, 0x0a, 0x04, 0x77,
	0x39, 0x30, 0x30, 0x10, 0x84, 0x07, 0x12, 0x0a, 0x0a, 0x05, 0x77, 0x33, 0x36, 0x30, 0x30, 0x10,
	0x90, 0x1c, 0x12, 0x0b, 0x0a, 0x06, 0x77, 0x31, 0x34, 0x34, 0x30, 0x30, 0x10, 0xc0, 0x70, 0x12,
	0x0c, 0x0a, 0x06, 0x77, 0x38, 0x36, 0x34, 0x30, 0x30, 0x10, 0x80, 0xa3, 0x05, 0x22, 0xab, 0x01,
	0x0a, 0x0f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x32, 0x43, 0x0a, 0x11, 0x63,
	0x68, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x2e, 0x0a, 0x04, 0x4f, 0x48, 0x4c, 0x43, 0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x67, 0x65, 0x74, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x1a, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79,
	0x6f, 0x65, 0x72, 0x69, 0x61, 0x2f, 0x67, 0x6f, 0x66, 0x74, 0x78, 0x6c, 0x6f, 0x67, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData = file_gateway_proto_rawDesc
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_proto_rawDescData)
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_proto_goTypes = []interface{}{
	(GetWindowWindowSizeSelector)(0), // 0: main.getWindow.windowSizeSelector
	(*GetWindow)(nil),                // 1: main.getWindow
	(*WindowDataArray)(nil),          // 2: main.windowDataArray
}
var file_gateway_proto_depIdxs = []int32{
	0, // 0: main.getWindow.windowSize:type_name -> main.getWindow.windowSizeSelector
	1, // 1: main.chartDataExchange.OHLC:input_type -> main.getWindow
	2, // 2: main.chartDataExchange.OHLC:output_type -> main.windowDataArray
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWindow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowDataArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_rawDesc = nil
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
